package com.ike.sq.alliance.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ike.sq.alliance.bean.FriendGroup;
import com.ike.sq.alliance.bean.GroupBean;
import com.ike.sq.alliance.bean.GroupMember;
import com.ike.sq.alliance.bean.Msg;

import com.ike.sq.alliance.dao.FriendGroupDao;
import com.ike.sq.alliance.dao.GroupBeanDao;
import com.ike.sq.alliance.dao.GroupMemberDao;
import com.ike.sq.alliance.dao.MsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendGroupDaoConfig;
    private final DaoConfig groupBeanDaoConfig;
    private final DaoConfig groupMemberDaoConfig;
    private final DaoConfig msgDaoConfig;

    private final FriendGroupDao friendGroupDao;
    private final GroupBeanDao groupBeanDao;
    private final GroupMemberDao groupMemberDao;
    private final MsgDao msgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendGroupDaoConfig = daoConfigMap.get(FriendGroupDao.class).clone();
        friendGroupDaoConfig.initIdentityScope(type);

        groupBeanDaoConfig = daoConfigMap.get(GroupBeanDao.class).clone();
        groupBeanDaoConfig.initIdentityScope(type);

        groupMemberDaoConfig = daoConfigMap.get(GroupMemberDao.class).clone();
        groupMemberDaoConfig.initIdentityScope(type);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        friendGroupDao = new FriendGroupDao(friendGroupDaoConfig, this);
        groupBeanDao = new GroupBeanDao(groupBeanDaoConfig, this);
        groupMemberDao = new GroupMemberDao(groupMemberDaoConfig, this);
        msgDao = new MsgDao(msgDaoConfig, this);

        registerDao(FriendGroup.class, friendGroupDao);
        registerDao(GroupBean.class, groupBeanDao);
        registerDao(GroupMember.class, groupMemberDao);
        registerDao(Msg.class, msgDao);
    }
    
    public void clear() {
        friendGroupDaoConfig.clearIdentityScope();
        groupBeanDaoConfig.clearIdentityScope();
        groupMemberDaoConfig.clearIdentityScope();
        msgDaoConfig.clearIdentityScope();
    }

    public FriendGroupDao getFriendGroupDao() {
        return friendGroupDao;
    }

    public GroupBeanDao getGroupBeanDao() {
        return groupBeanDao;
    }

    public GroupMemberDao getGroupMemberDao() {
        return groupMemberDao;
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

}
